services:
  db:
    image: postgres:16
    container_name: mini-blog-db
    networks:
      - mini-blog-net
    environment:
      POSTGRES_DB: miniblog
      POSTGRES_USER: miniblog
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: ghcr.io/dayho00/mini-blog-api:latest
    container_name: mini-blog-api
    networks:
      - mini-blog-net
    ports:
      - "8080:8080" # ✅ 추가: EC2 호스트(외부)에서 8080 접근 가능
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mini-blog-db
      DB_PORT: 5432
      DB_NAME: miniblog
      DB_USER: miniblog
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    restart: always

  web:
    image: ghcr.io/dayho00/mini-blog-web:latest
    container_name: mini-blog-web
    networks:
      - mini-blog-net
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

networks:
  mini-blog-net:
    driver: bridge

volumes:
  db_data:
