services:
  db:
    image: postgres:16
    container_name: mini-blog-db
    environment:
      POSTGRES_DB: miniblog
      POSTGRES_USER: mini
      POSTGRES_PASSWORD: mini1234
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
