services:
  db:
    image: postgres:16
    container_name: mini-blog-db
    environment:
      POSTGRES_DB: miniblog
      POSTGRES_USER: mini
      POSTGRES_PASSWORD: mini1234
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    image: ghcr.io/dayho00/mini-blog-api:latest
    container_name: mini-blog-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/miniblog
      SPRING_DATASOURCE_USERNAME: mini
      SPRING_DATASOURCE_PASSWORD: mini1234
    ports:
      - "8080:8080"
    depends_on:
      - db

  web:
    image: ghcr.io/dayho00/mini-blog-web:latest
    container_name: mini-blog-web
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  dbdata:
